{
  "controls": {
    "logLevel": "silly",
    "logFilename": "/var/log/cloud/bigIpRuntimeInit.log"
  },
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.39.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.39.0-4.noarch.rpm",
        "extensionHash": "4a67449195a53683a159b42857edd49a757da1a5a2029ccf94c4d6aa11ae4cda"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.46.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.46.0/f5-appsvcs-3.46.0-5.noarch.rpm",
        "extensionHash": "9550bcdcd1ffe1f002fa5e3c71b8818877d9c7e161f5c68027c82ad85e56e924"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.25.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.25.0/f5-appsvcs-templates-1.25.0-1.noarch.rpm",
        "extensionHash": "434309179af405e6b663e255d4d3c0a1fd45cac9b561370e350bb8dd8b39761f"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
