controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
runtime_parameters:
  - name: AZURE_SERVICE_PRINCIPAL
    type: secret
    secretProvider:
      type: KeyVault
      environment: azure
      vault: my-keyvault.vault.azure.net
    secretName: my_azure_secret
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
bigip_ready_enabled:
  - name: provision_asm_module
    type: inline
    commands:
      - tmsh modify sys provision asm level nominal
  - name: save_sys_config
    type: inline
    commands:
      - tmsh save sys config
post_onboard_enabled: []
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.33.0
    - extensionType: as3
      extensionVersion: 3.40.0
extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/examples/modules/autoscale_bigip/do.json
    - extensionType: as3
      type: url
      value: https://cdn.f5.com/product/cloudsolutions/f5-azure-arm-templates/examples/modules/autoscale_bigip/as3.json
