{
  "controls": {
    "logLevel": "silly",
    "logFilename": "/var/log/cloud/bigIpRuntimeInit.log"
  },
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.31.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.31.0-6.noarch.rpm",
        "extensionHash": "8c31d858f78100ce866b70fdf73ebc47f05adbdd2e62ac6ecc4a2162645fc852"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.38.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.38.0/f5-appsvcs-3.38.0-4.noarch.rpm",
        "extensionHash": "38b9b96826c2da997750ba2054811d8606768df43d08b870d68f8d7cb3fff58d"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.19.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.19.0/f5-appsvcs-templates-1.19.0-1.noarch.rpm",
        "extensionHash": "981b00b61c3dfc3d13f9e96836b6260aa250dc4b92fc7cb746b7ca7b2dbcea1d"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
