{
  "controls": {
    "logLevel": "silly",
    "logFilename": "/var/log/cloud/bigIpRuntimeInit.log"
  },
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.33.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.33.0-7.noarch.rpm",
        "extensionHash": "4ac7b7c6eb93320df20f964f32ce7bc6e0454858a36440761f774a8a42a01020"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.40.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.40.0/f5-appsvcs-3.40.0-5.noarch.rpm",
        "extensionHash": "708533815cb8e608b4d28fbb730f0ed34617ce5def53c5462c0ab98bd54730fc"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.21.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.21.0/f5-appsvcs-templates-1.21.0-1.noarch.rpm",
        "extensionHash": "9b637713abf07ba33d99b67c85cd8267556cceb1a0ed2816ef19306f330104c5"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
