{
  "controls": {
    "logLevel": "silly",
    "logFilename": "/var/log/cloud/bigIpRuntimeInit.log"
  },
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.41.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.41.0-8.noarch.rpm",
        "extensionHash": "3044e7ea1c8d7e10f51ec14a895374a956b3cbe3251dd6916f4f97da65d0a8e6"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.48.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.48.0/f5-appsvcs-3.48.0-10.noarch.rpm",
        "extensionHash": "d732b0e5e462bd5a7b253022ed13dd72afcc30696f0606f4acef47ec02dc31bb"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.25.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.25.0/f5-appsvcs-templates-1.25.0-1.noarch.rpm",
        "extensionHash": "434309179af405e6b663e255d4d3c0a1fd45cac9b561370e350bb8dd8b39761f"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
