{
  "controls": {
    "logLevel": "silly",
    "logFilename": "/var/log/cloud/bigIpRuntimeInit.log"
  },
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.36.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.36.0-4.noarch.rpm",
        "extensionHash": "6f94718afcbf7743b9c260ab341f33987d2d442ab1f5076410ebd557be7d2ff0"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.43.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.43.0/f5-appsvcs-3.43.0-2.noarch.rpm",
        "extensionHash": "6e50f828292c3e9417136693b7fba232ca4c004187ae1499e83e39210b500e7a"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.24.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.24.0/f5-appsvcs-templates-1.24.0-1.noarch.rpm",
        "extensionHash": "7f1c8080b6712915d18caaf3410d8ed21c0454f53bfc8999f294bd958231b47f"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
