controls:
  logLevel: silly
  logFilename: "/var/log/cloud/bigIpRuntimeInit.log"
runtime_parameters: []
pre_onboard_enabled:
- name: provision_rest
  type: inline
  commands:
    - "/usr/bin/setdb provision.extramb 500"
    - "/usr/bin/setdb restjavad.useextramb true"
bigip_ready_enabled:
- name: provision_asm_module
  type: inline
  commands:
    - tmsh modify sys provision asm level nominal
- name: save_sys_config
  type: inline
  commands:
    - tmsh save sys config
extension_packages:
  install_operations:
  - extensionType: do
    extensionVersion: 1.34.0
    extensionUrl: file:///var/config/rest/downloads/f5-declarative-onboarding-1.34.0-5.noarch.rpm
    extensionHash: 5e58bc15a4c436494599dfc509c87f02400339e6c0ce8275df259d5f1585146b
  - extensionType: as3
    extensionVersion: 3.41.0
    extensionUrl: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.41.0/f5-appsvcs-3.41.0-1.noarch.rpm
    extensionHash: ced0948208f4dc29af7c0ea3a925a28bf8b8690a263588374e3c3d2689999490
  - extensionType: fast
    extensionVersion: 1.22.0
    extensionUrl: https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.22.0/f5-appsvcs-templates-1.22.0-1.noarch.rpm
    extensionHash: 71a1c826aaf1f8a0c2ffc3c2f7f6b40c881f51e15da471411b423339b9e65030
  - extensionType: ilx
    extensionUrl: file:///var/config/rest/downloads/myIlxApp.rpm
    extensionVerificationEndpoint: "/mgmt/shared/myIlxApp/info"
