controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.30.0
    - extensionType: as3
      extensionVersion: 3.36.1
    - extensionType: fast
      extensionVersion: 1.19.0
extension_services:
  service_operations:
    - extensionType: as3
      type: inline
      value:
        class: AS3
        action: deploy
        persist: true
        declaration:
          class: ADC
          schemaVersion: 3.0.0
          id: urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d
          label: Sample 1
          remark: Simple HTTP Service with Round-Robin Load Balancing
          Sample_01:
            class: Tenant
            A1:
              class: Application
              template: http
              serviceMain:
                class: Service_HTTP
                virtualAddresses:
                  - 10.0.1.10
                pool: web_pool
              web_pool:
                class: Pool
                monitors:
                  - http
                members:
                  - servicePort: 80
                    serverAddresses:
                      - 192.0.1.10
                      - 192.0.1.11
