controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      type: Vault
      environment: hashicorp
      vaultServer: http://127.0.0.1:8200
      secretsEngine: kv2
      secretId: secret/foo
      field: password
      version: 1
      authBackend:
        type: approle
        roleId:
          type: url
          value: file:///path/to/role-id
        secretId:
          type: inline
          value: secret-id
          unwrap: true
  - name: SECOND_PASS
    type: secret
    secretProvider:
      type: Vault
      environment: hashicorp
      vaultServer: http://127.0.0.1:8200
      secretsEngine: kv2
      secretId: secret/bar
      field: data
      version: 1
      authBackend:
        type: approle
        roleId:
          type: url
          value: file:///path/to/role-id
        secretId:
          type: inline
          value: secret-id
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.37.0
    - extensionType: as3
      extensionVersion: 3.44.0
    - extensionType: fast
      extensionVersion: 1.24.0
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        async: true
        label: my BIG-IP declaration for declarative onboarding
        Common:
          class: Tenant
          hostname: '{{ HOST_NAME }}.local'
          admin:
            class: User
            userType: regular
            password: '{{ ADMIN_PASS }}'
            shell: bash
          admin2:
            class: User
            userType: regular
            password: '{{ SECOND_PASS.admin2_password }}'
            shell: bash
            partitionAccess:
              all-partitions:
                role: admin
          dbvars:
            class: DbVariables
            provision.extramb: 500
            restjavad.useextramb: true
