controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
bigip_ready_enabled:
  - name: set_message_size
    type: inline
    commands:
      - '/usr/bin/curl -s -f -u admin: -H "Content-Type: application/json" -d ''{"maxMessageBodySize":134217728}''
        -X POST http://localhost:8100/mgmt/shared/server/messaging/settings/8100 |
        jq .'
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.34.0
      extensionHash: 5e58bc15a4c436494599dfc509c87f02400339e6c0ce8275df259d5f1585146b
    - extensionType: as3
      extensionVersion: 3.41.0
      extensionHash: ced0948208f4dc29af7c0ea3a925a28bf8b8690a263588374e3c3d2689999490
    - extensionType: fast
      extensionVersion: 1.22.0
      extensionHash: 71a1c826aaf1f8a0c2ffc3c2f7f6b40c881f51e15da471411b423339b9e65030
extension_services:
  service_operations:
    - extensionType: as3
      type: url
      value: file:///examples/automation_toolchain_declarations/as3.json
