controls: {logLevel: "silly", logFilename: "/var/log/cloud/bigIpRuntimeInit.log"}
extension_packages: {install_operations: [{extensionType: "do", extensionVersion: "1.33.0",
      extensionHash: "4ac7b7c6eb93320df20f964f32ce7bc6e0454858a36440761f774a8a42a01020"},
    {extensionType: "as3", extensionUrl: "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.40.0/f5-appsvcs-3.40.0-5.noarch.rpm",
      extensionVersion: "3.40.0", verifyTls: false}, {extensionType: "ilx", extensionUrl: "file:///var/config/rest/downloads/myIlxApp.rpm",
      extensionVersion: "1.0.0", extensionVerificationEndpoint: "/mgmt/shared/myIlxApp/info"}]}
extension_services: {service_operations: [{extensionType: "do", type: "url", value: "https://cdn.f5.com/product/cloudsolutions/declarations/autoscale-waf/autoscale_do_payg.json",
      verifyTls: false}, {extensionType: "as3", type: "url", value: "https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/bigip/autoscale_as3.json"}]}
post_hook: [{name: "example_webhook", type: "webhook", url: "https://postman-echo.com/post",
    verifyTls: false, properties: {optionalKey1: "optional_value1", optionalKey2: "optional_value2"}}]
post_onboard_enabled: [{name: "example_inline_command", type: "inline", commands: [
      "touch /tmp/post_onboard_script.sh", "chmod 777 /tmp/post_onboard_script.sh",
      "echo \"touch /tmp/created_by_autogenerated_post_local\" > /tmp/post_onboard_script.sh"]},
  {name: "example_local_exec", type: "file", commands: ["/tmp/post_onboard_script.sh"]},
  {name: "example_remote_exec", type: "url", verifyTls: false, commands: ["https://ak-metadata-package-poc.s3.amazonaws.com/remote_post_onboard.sh"]},
  {name: "example_remote_exec", type: "url", commands: ["https://ak-metadata-package-poc.s3.amazonaws.com/remote_post_onboard.sh"]}]
pre_onboard_enabled: [{name: "example_remote_exec", type: "url", commands: ["https://ak-metadata-package-poc.s3.amazonaws.com/remote_pre_onboard.sh"]},
  {name: "provision_rest", type: "inline", commands: ["/usr/bin/setdb provision.extramb\
        \ 500", "/usr/bin/setdb restjavad.useextramb true"]}]
