{
  "controls": {
    "logLevel": "silly",
    "logFilename": "/var/log/cloud/bigIpRuntimeInit.log"
  },
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.39.0-4.noarch.rpm",
        "extensionHash": "4a67449195a53683a159b42857edd49a757da1a5a2029ccf94c4d6aa11ae4cda",
        "extensionVersion": "1.39.0"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVersion": "1.0.0",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info",
        "extensionHash": "de615341b91beaed59195dceefc122932580d517600afce1ba8d3770dfe42d28"
      }
    ]
  },
  "extension_services": {
    "service_operations": [
      {
        "extensionType": "do",
        "type": "url",
        "value": "file:///var/config/rest/downloads/do.json"
      }
    ]
  }
}
