controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
runtime_parameters:
  - name: SCHEMA_VERSION
    type: static
    value: 3.0.0
  - name: HOST_NAME
    type: static
    value: bigip1.example.com
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.39.0
    - extensionType: as3
      extensionVersion: 3.46.0
    - extensionType: fast
      extensionVersion: 1.25.0
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: "{{{ SCHEMA_VERSION }}}"
        class: Device
        async: true
        label: my BIG-IP declaration for declarative onboarding
        Common:
          class: Tenant
          hostname: "{{{ HOST_NAME }}}"
          myDns:
            class: DNS
            nameServers:
              - 8.8.8.8
          myNtp:
            class: NTP
            servers:
              - 0.pool.ntp.org
            timezone: UTC
          myProvisioning:
            class: Provision
            ltm: nominal
            asm: nominal
          dbvars:
            class: DbVariables
            provision.extramb: 500
            restjavad.useextramb: true
    - extensionType: as3
      type: inline
      value:
        class: AS3
        action: deploy
        persist: true
        declaration:
          class: ADC
          schemaVersion: "{{{ SCHEMA_VERSION }}}"
          label: Sample 1
          remark: Simple HTTP Service with Round-Robin Load Balancing
          Sample_01:
            class: Tenant
            A1:
              class: Application
              template: http
              serviceMain:
                class: Service_HTTP
                virtualAddresses:
                  - 10.0.1.10
                pool: web_pool
              web_pool:
                class: Pool
                monitors:
                  - http
                members:
                  - servicePort: 80
                    serverAddresses:
                      - 192.0.1.10
                      - 192.0.1.11
