webhook:
  description: Sends webhook payload to specified URL
  post_hook:
    - name: example_webhook
      type: webhook
      url: https://webhook.site
custom_properties:
  description: Sends webhook payload with user-specified custom properties
  post_hook:
    - name: example_webhook
      type: webhook
      url: https://webhook.site
      properties:
        optionalKey1: optional_value1
        optionalKey2: optional_value2