controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit.log
runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      environment: gcp
      type: SecretsManager
      version: latest
      secretId: ${secret_id}
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.27.0
    - extensionType: as3
      extensionVersion: 3.34.0
    - extensionType: fast
      extensionVersion: 1.15.0
    - extensionType: ts
      extensionVersion: 1.26.0
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        label: >-
          Quickstart 1NIC BIG-IP declaration for Declarative Onboarding with BYOL
          license
        async: true
        Common:
          class: Tenant
          My_DbVariables:
            class: DbVariables
            provision.extramb: 1000
            restjavad.useextramb: true
            ui.advisory.enabled: true
            ui.advisory.color: blue
            ui.advisory.text: BIG-IP Quickstart
          My_Provisioning:
            class: Provision
            asm: nominal
            ltm: nominal
          My_Ntp:
            class: NTP
            servers:
              - 169.254.169.253
            timezone: UTC
          My_Dns:
            class: DNS
            nameServers:
              - 169.254.169.253
          My_License:
            class: License
            licenseType: regKey
            regKey: AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEE
          My_System:
            class: System
            autoPhonehome: true
            hostname: 'HOST_NAME'
          quickstart:
            class: User
            partitionAccess:
              all-partitions:
                role: admin
            password: 'BIGIP_PASSWORD'
            shell: bash
            userType: regular