aws:
  description: AWS Example
  controls:
    logLevel: silly
    logFilename: /var/log/cloud/bigIpRuntimeInit.log
  runtime_parameters:
    - name: ADMIN_PASS
      type: secret
      secretProvider:
        type: SecretManager
        environment: aws
        version: AWSCURRENT
        secretId: test-document-01
    - name: HOST_NAME
      type: metadata
      metadataProvider:
        environment: aws
        type: compute
        field: hostname
    - name: SELF_IP_EXTERNAL
      type: metadata
      metadataProvider:
        environment: aws
        type: network
        field: local-ipv4s
        index: 1
    - name: SELF_IP_INTERNAL
      type: metadata
      metadataProvider:
        environment: aws
        type: network
        field: local-ipv4s
        index: 2
    - name: DEFAULT_ROUTE
      type: metadata
      metadataProvider:
        environment: aws
        type: network
        field: subnet-ipv4-cidr-block
        index: 1
azure:
  description: Azure Example
  controls:
    logLevel: silly
    logFilename: /var/log/cloud/bigIpRuntimeInit.log
  runtime_parameters:
    - name: AZURE_SERVICE_PRINCIPAL
      type: secret
      secretProvider:
        type: KeyVault
        environment: azure
        vaultUrl: https://my-keyvault.vault.azure.net
        secretId: my_azure_secret
    - name: HOST_NAME
      type: metadata
      metadataProvider:
        environment: azure
        type: compute
        field: name
    - name: SELF_IP_INTERNAL
      type: metadata
      metadataProvider:
        environment: azure
        type: network
        field: ipv4
        index: 1
    - name: SELF_IP_EXTERNAL
      type: metadata
      metadataProvider:
        environment: azure
        type: network
        field: ipv4
        index: 2
gcp:
  description: Google Example
  controls:
    logLevel: silly
    logFilename: /var/log/cloud/bigIpRuntimeInit.log
  runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      type: SecretsManager
      environment: gcp
      version: latest
      secretId: my-secret-id-01
  - name: ROOT_PASS
    type: secret
    secretProvider:
      type: SecretsManager
      environment: gcp
      version: latest
      secretId: my-secret-id-02
  - name: HOST_NAME
    type: metadata
    metadataProvider:
        environment: gcp
        type: compute
        field: name
hashicorp:
  description: Hashicorp Vault Example
  controls:
    logLevel: silly
    logFilename: /var/log/cloud/bigIpRuntimeInit.log
  runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      type: Vault
      environment: hashicorp
      vaultServer: http://127.0.0.1:8200
      secretsEngine: kv2
      secretId: secret/foo
      field: password
      version: 1
      authBackend:
        type: approle
        roleId:
          type: url
          value: file:///path/to/role-id
        secretId:
          type: inline
          value: secret-id
          unwrap: true