{
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.26.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.26.0-5.noarch.rpm",
        "extensionHash": "f1f4a23cd7d3ac3d9f38fed520c373f5a16284fab001ebd26593ddc97c011ef3"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.33.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.33.0/f5-appsvcs-3.33.0-4.noarch.rpm",
        "extensionHash": "90a21684d764934d73588007e02b45e8328b76c63130591670f362e4b02140a3"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.14.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.14.0/f5-appsvcs-templates-1.14.0-1.noarch.rpm",
        "extensionHash": "dafa15dbcc41742866dcffb4fc2ebe72615b7e47d6443311af3630e15f49e7c9"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
