runtime_parameters:
  - name: HOST_NAME
    type: metadata
    metadataProvider:
      environment: azure
      type: compute
      field: name
  - name: SELF_IP_INTERNAL
    type: metadata
    metadataProvider:
      environment: azure
      type: network
      field: ipv4
      index: 2
  - name: SELF_IP_EXTERNAL
    type: metadata
    metadataProvider:
      environment: azure
      type: network
      field: ipv4
      index: 1
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
bigip_ready_enabled:
  - name: provision_asm_module
    type: inline
    commands:
      - tmsh modify sys provision asm level nominal
  - name: save_sys_config
    type: inline
    commands:
      - tmsh save sys config
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.22.0
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value:
        schemaVersion: 1.0.0
        class: Device
        async: true
        label: my BIG-IP declaration for declarative onboarding
        Common:
          class: Tenant
          hostname: "{{{ HOST_NAME }}}.local"
          internal:
            class: VLAN
            tag: 4093
            mtu: 1500
            interfaces:
              - name: '1.2'
                tagged: true
          internal-self:
            class: SelfIp
            address: "{{{ SELF_IP_INTERNAL }}}"
            vlan: internal
            allowService: default
            trafficGroup: traffic-group-local-only
          external:
            class: VLAN
            tag: 4094
            mtu: 1500
            interfaces:
              - name: '1.1'
                tagged: true
          external-self:
            class: SelfIp
            address: "{{{ SELF_IP_EXTERNAL }}}"
            vlan: external
            allowService: none
            trafficGroup: traffic-group-local-only
          provision:
            class: Provision
            ltm: nominal
            gtm: minimum
post_hook:
  - name: example_webhook
    type: webhook
    url: https://postman-echo.com/post
    verifyTls: true
    properties:
      optionalKey1: optional_value1
      optionalKey2: optional_value2
