{
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    },
    {
      "name": "provision_modules",
      "type": "inline",
      "commands": [
        "echo 'sys provision asm { level nominal }' >> bigip_base.conf"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.17.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.17.0-3.noarch.rpm",
        "extensionHash": "a359aa8aa14dc565146d4ccc413f169f1e8d02689559c5e4a652f91609a55fbb"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.24.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.24.0/f5-appsvcs-3.24.0-5.noarch.rpm",
        "extensionHash": "df786fc755c5de6f3fcc47638caf3db4c071fcd9cf37855de78fd7e25e5117b4"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/f5-appsvcs-templates-1.1.0-1.noarch.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/fast/info"
      }
    ]
  }
}
