{
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.17.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.17.0-3.noarch.rpm",
        "extensionHash": "a359aa8aa14dc565146d4ccc413f169f1e8d02689559c5e4a652f91609a55fbb"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.24.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.24.0/f5-appsvcs-3.24.0-5.noarch.rpm",
        "extensionHash": "df786fc755c5de6f3fcc47638caf3db4c071fcd9cf37855de78fd7e25e5117b4"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.5.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.5.0/f5-appsvcs-templates-1.5.0-1.noarch.rpm",
        "extensionHash": "57c05971d56200824398d8c678f67e65d74ea534348e55ab7c793a270c57ed3c"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
