{
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.20.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.20.0-2.noarch.rpm",
        "extensionHash": "02d29e99f76b1f9e2c99d4aee6dc73873f78735f430fe53139ca51c2d5f1fead"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.27.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.27.0/f5-appsvcs-3.27.0-3.noarch.rpm",
        "extensionHash": "67b922b0f1c61222ba571ff8cadfe7cbd34dd94712fc1c778efd27448c5992a9"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.8.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.8.0/f5-appsvcs-templates-1.8.0-1.noarch.rpm",
        "extensionHash": "cc96297ff5349d33ba84ea500f9f55c6d1f82ebaf97d61dbef44e371b146f79a"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
