{
  "runtime_parameters": [],
  "pre_onboard_enabled": [
    {
      "name": "provision_rest",
      "type": "inline",
      "commands": [
        "/usr/bin/setdb provision.extramb 500",
        "/usr/bin/setdb restjavad.useextramb true"
      ]
    }
  ],
  "bigip_ready_enabled": [
    {
      "name": "provision_asm_module",
      "type": "inline",
      "commands": [
        "tmsh modify sys provision asm level nominal"
      ]
    },
    {
      "name": "save_sys_config",
      "type": "inline",
      "commands": [
        "tmsh save sys config"
      ]
    }
  ],
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.22.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-declarative-onboarding-1.22.0-3.noarch.rpm",
        "extensionHash": "92c2aa88c6de685a4f40f5cbbde13afacc906cbc418e4b68ba66c98c7eabae4d"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.29.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.29.0/f5-appsvcs-3.29.0-3.noarch.rpm",
        "extensionHash": "bcbba79b42b700b8d2b46937b65e6d09b035515a7a7e40aaeebb360fcfe7aa66"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.10.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.10.0/f5-appsvcs-templates-1.10.0-1.noarch.rpm",
        "extensionHash": "30819184406499649b63f8f6a5d5f4eda3a38a89fa8043ecd58c2f190c0eec73"
      },
      {
        "extensionType": "ilx",
        "extensionUrl": "file:///var/config/rest/downloads/myIlxApp.rpm",
        "extensionVerificationEndpoint": "/mgmt/shared/myIlxApp/info"
      }
    ]
  }
}
