runtime_parameters:
  - name: AZURE_SERVICE_PRINCIPAL
    type: secret
    secretProvider:
      type: KeyVault
      environment: azure
      vaultUrl: https://my-keyvault.vault.azure.net
      secretId: my_azure_secret
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.17.0
    - extensionType: as3
      extensionVersion: 3.24.0
    - extensionType: fast
      extensionVersion: 1.5.0
extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/bigip/autoscale_do.json
    - extensionType: as3
      type: url
      value: file:///examples/declarations/example_3_as3.json
