pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.21.1
    - extensionType: as3
      extensionVersion: 3.28.0
    - extensionType: fast
      extensionVersion: 1.9.0
post_hook:
  - name: example_webhook
    type: webhook
    url: https://webhook.site
    verifyTls: true
    properties:
      optionalKey1: optional_value1
      optionalKey2: optional_value2
