runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      type: SecretManager
      environment: aws
      version: AWSCURRENT
      secretId: test-document-01
  - name: ROOT_PASS
    type: secret
    secretProvider:
      type: SecretManager
      environment: aws
      version: AWSCURRENT
      secretId: test-document-02
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.19.0
    - extensionType: as3
      extensionVersion: 3.26.0
    - extensionType: fast
      extensionVersion: 1.7.0
extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: file:///examples/declarations/example_4_do.json
