description: Verifies and installs packages using specified hashes
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.17.0
      extensionHash: a359aa8aa14dc565146d4ccc413f169f1e8d02689559c5e4a652f91609a55fbb
    - extensionType: as3
      extensionVersion: 3.24.0
      extensionHash: eaef5c650da84f593d17939e3bb5d649097f60a6d302d6abc06951f2b4a986d9
