description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.25.0
    - extensionType: as3
      extensionVersion: 3.32.0
    - extensionType: fast
      extensionVersion: 1.13.0
