description: Verifies and installs packages using specified hashes
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.22.0
      extensionHash: 92c2aa88c6de685a4f40f5cbbde13afacc906cbc418e4b68ba66c98c7eabae4d
    - extensionType: as3
      extensionVersion: 3.29.0
      extensionHash: bcbba79b42b700b8d2b46937b65e6d09b035515a7a7e40aaeebb360fcfe7aa66
    - extensionType: fast
      extensionVersion: 1.10.0
      extensionHash: 30819184406499649b63f8f6a5d5f4eda3a38a89fa8043ecd58c2f190c0eec73
