description: Verifies and installs packages using specified hashes
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.21.1
      extensionHash: 4ddf98bfec0f6272ac1c76a81b806fc1f16bae03f39a74e2468b2b0e7b96be09
    - extensionType: as3
      extensionVersion: 3.28.0
      extensionHash: b45f1762dbec90e953f825c4f7b3628f44c2404af627f2400dccc4996ef98979
    - extensionType: fast
      extensionVersion: 1.9.0
      extensionHash: 0c0ac07191229e083d6c903f5aea5250ff1828ed9268f8ecb89b19f5683348e9
