description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.21.1
    - extensionType: as3
      extensionVersion: 3.28.0
    - extensionType: fast
      extensionVersion: 1.9.0
