{
  "description": "Installs packages from custom locations",
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.20.0",
        "extensionUrl": "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.20.0/f5-declarative-onboarding-1.20.0-2.noarch.rpm"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.27.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-appsvcs-3.27.0-3.noarch.rpm"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.8.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.8.0/f5-appsvcs-templates-1.8.0-1.noarch.rpm"
      }
    ]
  }
}
