description: Verifies and installs packages using specified hashes
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.26.0
      extensionHash: f1f4a23cd7d3ac3d9f38fed520c373f5a16284fab001ebd26593ddc97c011ef3
    - extensionType: as3
      extensionVersion: 3.33.0
      extensionHash: 368d7b22738fe707655ca3a104c7c79c5c185eb07021e41eebe0e19d70ca63ee
    - extensionType: fast
      extensionVersion: 1.14.0
      extensionHash: dafa15dbcc41742866dcffb4fc2ebe72615b7e47d6443311af3630e15f49e7c9
