description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.19.0
    - extensionType: as3
      extensionVersion: 3.26.0
    - extensionType: fast
      extensionVersion: 1.7.0
