description: Verifies and installs packages using specified hashes
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.25.0
      extensionHash: 2c990f6185b16acf0234ebba02afc24863f538c955f51c7a3ebe01d5db58b859
    - extensionType: as3
      extensionVersion: 3.32.0
      extensionHash: a0746531a70b86316a68ab1eb9b3be5b18606f1bf0032ddc5c41a01c32d452a7
    - extensionType: fast
      extensionVersion: 1.13.0
      extensionHash: aeecdc04bbf6cb1012cb8d32ab191210b737c9f8b23a037fcacd2420f32dfe18
