{
  "description": "Installs packages from custom locations",
  "extension_packages": {
    "install_operations": [
      {
        "extensionType": "do",
        "extensionVersion": "1.25.0",
        "extensionUrl": "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.25.0/f5-declarative-onboarding-1.25.0-7.noarch.rpm"
      },
      {
        "extensionType": "as3",
        "extensionVersion": "3.32.0",
        "extensionUrl": "file:///var/config/rest/downloads/f5-appsvcs-3.32.0-4.noarch.rpm"
      },
      {
        "extensionType": "fast",
        "extensionVersion": "1.13.0",
        "extensionUrl": "https://github.com/F5Networks/f5-appsvcs-templates/releases/download/v1.13.0/f5-appsvcs-templates-1.13.0-1.noarch.rpm"
      }
    ]
  }
}
