description: Installs a custom iLX package
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.21.0
    - extensionType: as3
      extensionVersion: 3.28.0
    - extensionType: fast
      extensionVersion: 1.9.0
    - extensionType: ilx
      extensionUrl: file:///var/config/rest/downloads/myIlxApp.rpm
      extensionVersion: 1.0.0
      extensionVerificationEndpoint: /mgmt/shared/myIlxApp/info
