description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.17.0
    - extensionType: as3
      extensionVersion: 3.24.0
