description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.26.0
    - extensionType: as3
      extensionVersion: 3.33.0
    - extensionType: fast
      extensionVersion: 1.14.0
