description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.22.0
    - extensionType: as3
      extensionVersion: 3.29.0
    - extensionType: fast
      extensionVersion: 1.10.0
