description: Installs a custom iLX package
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.17.0
    - extensionType: as3
      extensionVersion: 3.24.0
    - extensionType: ilx
      extensionUrl: file:///var/config/rest/downloads/f5-appsvcs-templates-1.1.0-1.noarch.rpm
      extensionVersion: 1.1.0
      extensionVerificationEndpoint: /mgmt/shared/fast/info
