description: Installs packages using specific versions
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.23.0
    - extensionType: as3
      extensionVersion: 3.30.0
    - extensionType: fast
      extensionVersion: 1.11.0
