runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      type: Vault
      environment: hashicorp
      vaultServer: http://127.0.0.1:8200
      namespace: ns1/
      secretsEngine: kv2
      secretId: secret/foo
      field: password
      version: 1
      authBackend:
        type: approle
        roleId:
          type: url
          value: file:///path/to/role-id
        secretId:
          type: inline
          value: secret-id
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.22.0
    - extensionType: as3
      extensionVersion: 3.29.0
    - extensionType: fast
      extensionVersion: 1.10.0
    - extensionType: ts
      extensionVersion: 1.20.1
