#!/bin/bash

cat << 'EOF' > /config/onboard_config.yaml
---
controls:
  logLevel: silly
  logFilename: /var/log/cloud/bigIpRuntimeInit-test.log
  logToJson: true
  extensionInstallDelayInMs: 6000
runtime_parameters:
  - name: ADMIN_PASS
    type: secret
    secretProvider:
      type: KeyVault
      environment: azure
      vaultUrl: https://testvault-${deployment_id}.vault.${domain}.net
      secretId: test-azure-admin-secret
  - name: ROOT_PASS
    type: secret
    verifyTls: false
    secretProvider:
      type: Vault
      environment: hashicorp
      vaultServer: vault_server_public_http
      secretsEngine: kv2
      secretPath: kv/data/credential
      field: password
      version: "1"
      authBackend:
        type: approle
        roleId:
          type: inline
          value: vault_app_role
        secretId:
          type: inline
          value: vault_secret_id
          unwrap: false
  - name: SECOND_PASS
    type: secret
    verifyTls: false
    secretProvider:
      type: Vault
      environment: hashicorp
      vaultServer: vault_server_public_http
      secretsEngine: kv2
      secretPath: kv/data/credential
      field: data
      version: "1"
      authBackend:
        type: approle
        roleId:
          type: inline
          value: vault_app_role
        secretId:
          type: inline
          value: vault_wrapped_secret_id
          unwrap: true
  - name: HOST_NAME
    type: metadata
    metadataProvider:
      environment: azure
      type: compute
      field: name
  - name: SELF_IP_INTERNAL
    type: metadata
    metadataProvider:
      environment: azure
      type: network
      field: ipv4
      index: 1
  - name: SELF_IP_EXTERNAL
    type: metadata
    metadataProvider:
      environment: azure
      type: network
      field: ipv4
      index: 2
  - name: GATEWAY
    type: metadata
    metadataProvider:
      environment: azure
      type: network
      field: ipv4
      index: 2
      ipcalc: first
pre_onboard_enabled:
  - name: provision_rest
    type: inline
    commands:
      - /usr/bin/setdb provision.extramb 500
      - /usr/bin/setdb restjavad.useextramb true
bigip_ready_enabled:
  - name: provision_asm
    type: inline
    commands:
      - tmsh modify sys provision asm level nominal
  - name: example_inline_command
    type: inline
    commands:
      - touch /tmp/pre_onboard_script.sh
      - chmod 777 /tmp/pre_onboard_script.sh
      - echo "touch /tmp/created_by_autogenerated_pre_local" > /tmp/pre_onboard_script.sh
  - name: example_local_exec
    type: file
    commands:
      - /tmp/pre_onboard_script.sh
  - name: example_remote_exec
    type: url
    commands:
      - https://ak-metadata-package-poc.s3.amazonaws.com/remote_pre_onboard.sh
  - name: save_sys_config
    type: inline
    commands:
      - tmsh save sys config
post_onboard_enabled:
  - name: example_inline_command
    type: inline
    commands:
      - touch /tmp/post_onboard_script.sh
      - chmod 777 /tmp/post_onboard_script.sh
      - echo "touch /tmp/created_by_autogenerated_post_local" > /tmp/post_onboard_script.sh
  - name: example_local_exec
    type: file
    commands:
      - /tmp/post_onboard_script.sh
  - name: example_remote_exec
    type: url
    commands:
      - https://ak-metadata-package-poc.s3.amazonaws.com/remote_post_onboard.sh
    verifyTls: false
  - name: example_remote_exec
    type: url
    commands:
      - https://ak-metadata-package-poc.s3.amazonaws.com/remote_post_onboard.sh
extension_packages:
  install_operations:
    - extensionType: do
      extensionVersion: 1.23.0
    - extensionType: as3
      extensionVersion: 3.30.0
      verifyTls: false
      extensionUrl: https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.30.0/f5-appsvcs-3.30.0-5.noarch.rpm
      extensionHash: 47cc7bb6962caf356716e7596448336302d1d977715b6147a74a142dc43b391b
    - extensionType: fast
      extensionVersion: 1.11.0
    - extensionType: ilx
      extensionUrl: file:///var/config/rest/downloads/hello-world-0.1.0-0001.noarch.rpm
      extensionVerificationEndpoint: /mgmt/shared/echo
      extensionVersion: 0.1.0
extension_services:
  service_operations:
    - extensionType: do
      type: inline
      value: 
        schemaVersion: 1.0.0
        class: Device
        async: true
        label: my BIG-IP declaration for declarative onboarding
        Common:
          class: Tenant
          hostname: '{{ HOST_NAME }}.local'
          internal:
            class: VLAN
            tag: 4093
            mtu: 1500
            interfaces:
              - name: '1.2'
                tagged: true
          internal-self:
            class: SelfIp
            address: '{{{ SELF_IP_INTERNAL }}}'
            vlan: internal
            allowService: default
            trafficGroup: traffic-group-local-only
          external:
            class: VLAN
            tag: 4094
            mtu: 1500
            interfaces:
              - name: '1.1'
                tagged: true
          external-self:
            class: SelfIp
            address: '{{{ SELF_IP_EXTERNAL }}}'
            vlan: external
            allowService: default
            trafficGroup: traffic-group-local-only
          myDns:
            class: DNS
            nameServers:
              - 8.8.8.8
          myNtp:
            class: NTP
            servers:
              - 0.pool.ntp.org
            timezone: UTC
          myProvisioning:
            class: Provision
            ltm: nominal
            asm: nominal
          admin:
            class: User
            userType: regular
            password: '{{ ADMIN_PASS }}'
            shell: bash
          vaultadmin:
            class: User
            userType: regular
            password: '{{ ROOT_PASS }}'
            shell: bash
            partitionAccess:
              all-partitions:
                role: admin
          vaultadmin2:
            class: User
            userType: regular
            password: '{{ SECOND_PASS.bigiq_admin_password }}'
            shell: bash
            partitionAccess:
              all-partitions:
                role: admin
          dbvars:
            class: DbVariables
            provision.extramb: 500
            restjavad.useextramb: true
    - extensionType: as3
      type: url
      value: https://cdn.f5.com/product/cloudsolutions/templates/f5-azure-arm-templates/examples/modules/bigip/autoscale_as3.json
post_hook:
  - name: example_webhook
    type: webhook
    url: https://postman-echo.com/post
    properties:
      optionalKey1: optional_value1
      optionalKey2: optional_value2
